"""Frozen-weight architectural self-improvement experiment primitives."""

from .candidate_pool import (
    CandidatePoolError,
    CandidatePoolTask,
    FrozenCandidate,
    FrozenCandidatePool,
    GenerationSource,
    build_frozen_candidate_pool,
)
from .evaluation import (
    PolicyEvaluation,
    PolicyTaskScore,
    evaluate_policy_on_split,
)
from .experiment import (
    FinalistEvaluation,
    HiddenOpeningReport,
    PairedImprovement,
    SearchPhaseResult,
    deterministic_target_permutation,
    open_hidden_phase,
    run_search_phase,
)
from .generation import (
    TargetFreeGenerationArtifact,
    TargetFreeGenerationCase,
    build_pool_from_generation_artifacts,
    generate_target_free_artifact,
)
from .genome import (
    BehaviorDescriptor,
    IMMUTABLE_PARENT_GENOME,
    PolicyMode,
    ReasoningPolicyGenome,
)
from .manifests import (
    ExperimentSplit,
    FinalistEntry,
    FinalistManifest,
    FinalistRole,
    SelfImprovementExperimentManifest,
    SplitManifest,
    build_experiment_manifest,
    freeze_finalists,
)
from .mutation import (
    MutationRecord,
    ProposedMutation,
    apply_mutation,
    propose_neighbor_mutations,
)
from .policy import (
    PolicyExecution,
    PolicyResourceTrace,
    ReasoningBudget,
    execute_reasoning_policy,
)
from .search import (
    GenomeEvaluationRecord,
    PromotionEvent,
    SearchConfig,
    SearchResult,
    SearchStrategy,
    SplitFitness,
    enumerate_normalized_genomes,
    run_quality_diverse_search,
    run_random_search,
    run_single_best_search,
)

__all__ = [
    "BehaviorDescriptor",
    "CandidatePoolError",
    "CandidatePoolTask",
    "ExperimentSplit",
    "FinalistEntry",
    "FinalistEvaluation",
    "FinalistManifest",
    "FinalistRole",
    "FrozenCandidate",
    "FrozenCandidatePool",
    "GenerationSource",
    "GenomeEvaluationRecord",
    "HiddenOpeningReport",
    "IMMUTABLE_PARENT_GENOME",
    "MutationRecord",
    "PairedImprovement",
    "PolicyEvaluation",
    "PolicyExecution",
    "PolicyMode",
    "PolicyResourceTrace",
    "PolicyTaskScore",
    "PromotionEvent",
    "ProposedMutation",
    "ReasoningBudget",
    "ReasoningPolicyGenome",
    "SearchConfig",
    "SearchPhaseResult",
    "SearchResult",
    "SearchStrategy",
    "SelfImprovementExperimentManifest",
    "SplitFitness",
    "SplitManifest",
    "TargetFreeGenerationArtifact",
    "TargetFreeGenerationCase",
    "apply_mutation",
    "build_experiment_manifest",
    "build_frozen_candidate_pool",
    "build_pool_from_generation_artifacts",
    "deterministic_target_permutation",
    "enumerate_normalized_genomes",
    "evaluate_policy_on_split",
    "execute_reasoning_policy",
    "freeze_finalists",
    "generate_target_free_artifact",
    "open_hidden_phase",
    "propose_neighbor_mutations",
    "run_quality_diverse_search",
    "run_random_search",
    "run_search_phase",
    "run_single_best_search",
]
