"""Architecture-independent contracts for capable collective cognition."""

from .artifacts import (
    ARTIFACT_SCHEMA,
    EVALUATION_SCHEMA,
    CollectiveStage,
    EvaluationRecord,
    EvaluationVisibility,
    MetricValue,
    ResourceUsage,
    StageArtifact,
    TaskIdentity,
    sha256_content,
)
from .bakeoff import (
    BakeoffPlan,
    CandidateDiagnostic,
    CandidateModel,
    CandidateTaskResult,
    DeploymentClass,
    PopulationSelection,
    PopulationSelectionStatus,
    select_population,
)
from .content_store import (
    ContentIntegrityError,
    ContentStore,
    ContentStoreError,
    FileContentStore,
    content_sha256,
)
from .metrics import (
    CollectiveSummary,
    ErrorCorrelation,
    FourMindCredit,
    OutcomeTable,
    StageDelta,
    compare_stages,
    error_correlation_matrix,
    evaluate_four_mind_credit,
    pairwise_error_correlation,
    summarize_collective,
)
from .mind import MindBackend, MindIdentity, MindInvocationResult, MindRequest
from .repository import (
    REPOSITORY_SNAPSHOT_SCHEMA,
    RepositoryFile,
    RepositorySnapshot,
    StoredRepositorySnapshot,
    load_repository_snapshot,
    materialize_repository_snapshot,
    snapshot_directory,
)
from .repository_surgery import (
    GENERATION_RECORD_SCHEMA,
    REPOSITORY_SURGERY_FAMILY,
    SUBMISSION_SCHEMA,
    MutationKind,
    PatchFormat,
    RepositorySurgeryGenerationRecord,
    RepositorySurgerySubmission,
    build_visible_repository_surgery_task,
)
from .tasks import (
    ProtectedEvaluatorSpec,
    SolverVisibleTask,
    TaskResourceBudget,
    TaskSplit,
)

__all__ = [
    "ARTIFACT_SCHEMA",
    "EVALUATION_SCHEMA",
    "GENERATION_RECORD_SCHEMA",
    "REPOSITORY_SNAPSHOT_SCHEMA",
    "REPOSITORY_SURGERY_FAMILY",
    "SUBMISSION_SCHEMA",
    "BakeoffPlan",
    "CandidateDiagnostic",
    "CandidateModel",
    "CandidateTaskResult",
    "CollectiveStage",
    "CollectiveSummary",
    "ContentIntegrityError",
    "ContentStore",
    "ContentStoreError",
    "DeploymentClass",
    "ErrorCorrelation",
    "EvaluationRecord",
    "EvaluationVisibility",
    "FileContentStore",
    "FourMindCredit",
    "MetricValue",
    "MindBackend",
    "MindIdentity",
    "MindInvocationResult",
    "MindRequest",
    "MutationKind",
    "OutcomeTable",
    "PatchFormat",
    "PopulationSelection",
    "PopulationSelectionStatus",
    "ProtectedEvaluatorSpec",
    "RepositoryFile",
    "RepositorySnapshot",
    "RepositorySurgeryGenerationRecord",
    "RepositorySurgerySubmission",
    "ResourceUsage",
    "SolverVisibleTask",
    "StageArtifact",
    "StageDelta",
    "StoredRepositorySnapshot",
    "TaskIdentity",
    "TaskResourceBudget",
    "TaskSplit",
    "build_visible_repository_surgery_task",
    "compare_stages",
    "content_sha256",
    "error_correlation_matrix",
    "evaluate_four_mind_credit",
    "load_repository_snapshot",
    "materialize_repository_snapshot",
    "pairwise_error_correlation",
    "select_population",
    "sha256_content",
    "snapshot_directory",
    "summarize_collective",
]
